version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: treasurelock
    environment:
      - NODE_ENV=production
    ports:
      - "3991:3991"
    restart: unless-stopped